### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-stash#121]
we haven't released the module in a while :(

**Comment by rnelson0** [comment]
As stash was renamed to BitBucket, should the module name change yet?

**Comment by juniorsysadmin** [comment]
> As stash was renamed to BitBucket, should the module name change yet?

As the module attempts to do upgrades from Stash to Bitbucket. I would say no.

**Comment by igalic** [comment]
we should however, extend [our tags](https://github.com/voxpupuli/puppet-stash/blob/master/metadata.json#L11)

**Comment by tobru** [comment]
If ready - why not release now? Count my vote for a release... :+1:

**Comment by igalic** [comment]
you could create a release pr: https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module

**Comment by lreed** [comment]
I second that vote for a release.

Thanks

**Comment by ekohl** [comment]
There have been release since this was opened.
