### ISSUE TITLE
Installation does not work correctly with Stash >=3.2.0

### ISSUE THREAD

**Issue by awegmann** [voxpupuli/puppet-stash#16]
Atlassian changed the location of the config files for Stash with version 3.2.0.

A documentation can be found here: 
https://confluence.atlassian.com/display/STASHKB/Upgrading+your+Stash+home+directory+for+Stash+3.2+manually
## Problem:

`stash-config.properties` has moved to `shared/stash-config.properties`. If you upgrade Stash to a version >=3.2.0 or install this version, Stash will migrate the file and copy it to the `shared` folder. The puppet module will recreate it on next run. If Stash is restarted with both files existing, it refuses to work and assumes the automatic migration to the new version didn't work correctly.
## Possible Solution:

According to the version the fact for `stash-config.properties` should contain the new directory.

**Comment by mkrakowitzer** [comment]
This should be resolved now.
