### ISSUE TITLE
stash user homedir circular ordering problem

### ISSUE THREAD

**Issue by preflightsiren** [voxpupuli/puppet-stash#2]
creating a user with a non existant homedir results in an error with useradd

```
err: /User[stash]/ensure: change from absent to present failed: Could not create user stash: Execution of '/usr/sbin/useradd -s /bin/true -d /opt/atlassian/application-data/stash-home -c Stash daemon account -m stash' returned 12: useradd: cannot create directory /opt/atlassian/application-data/stash-home
```

looking at the code, the file resource needs the user to exist, but the user resource needs the file to exist.

``` puppet
 user { $stash::user:
    comment          => 'Stash daemon account',
    shell            => '/bin/true',
    home             => $stash::homedir,
    password         => '*',
    password_min_age => '0',
    password_max_age => '99999',
    managehome       => true,
    uid              => $stash::uid,
    gid              => $stash::gid,
  } ->
#...
file { $stash::homedir:
    ensure  => 'directory',
    owner   => $stash::user,
    group   => $stash::group,
  }
```

**Comment by preflightsiren** [comment]
I think a solution would be to create the folder first, then allow the user resource to modify the permissions to the folder.

**Comment by mkrakowitzer** [comment]
Manage home should create the homedir, I think we need to change the parent home directory or create it before. /opt/atlassian/application-data/ I will update this.

**Comment by mkrakowitzer** [comment]
I think this is an issue with my default example, if one just does

``` puppet
class { 'stash':
  group       => 'stashadm',
}
```

The default homedir will be /home/stash, and it sould just work fine.

**Comment by mkrakowitzer** [comment]
resolved.
