### ISSUE TITLE
Archiving this module

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/puppet-stash#208]
The discussion came up of this module should get archived. Should someone want to keep this module around, just comment here.
If no comments to keep this around arise in the new weeks, we will move forward with archiving.

**Comment by h-haaks** [comment]
We are currently using a fork of https://github.com/danofthewired/puppet-bitbucket which has not seen a release to forge in almost 4 years.
Is it possible to get the puppet-bitbucket module into voxpupuli as a replacement?

**Comment by zilchms** [comment]
I think this could be a good idea. I am not all to familiar with the migration process. But opening up an issue on danofthewired's repository seems like a good starting point. If he responds great, we can probably work something out. If he doesnt respond, we can fork it I think. Can you open the issue?

**Comment by h-haaks** [comment]
https://github.com/danofthewired/puppet-bitbucket/issues/84

**Comment by ShadNex** [comment]
@zilchms there has been no comment from danofthewired regarding h-haaks' request for migration to Voxpopuli in ~3 months. Do you think you could proceed with forking the repository? Additionally, we're currently using a fork of this repository in our own environment, which would greatly benefit from a publically maintained Puppet module.

**Comment by zilchms** [comment]
I think we  can proceed with forking. @h-haaks Do you have time to work on that ? I am currently a bit swamped with work

**Comment by bastelfreak** [comment]
I think it's save to archive the stash module now. And when people want to step up and work on a bitbucket module, we can discuss that in our IRC/slack channel.
