### ISSUE TITLE
Debian support and optional Java dependency

### ISSUE THREAD

**Issue by pdirksen** [voxpupuli/puppet-stash#24]
Please support debian (wheezy) explicitely.

Keep up the good work!

**Comment by mkrakowitzer** [comment]
Will make sure I add debian support for next forge release. Please clarify what you mean by optional Java dependency?

**Comment by pdirksen** [comment]
We use the java module from puppetlabs to install the jdk/jre. It would be nice if JAVA_HOME would be detected automatically.
Furthermore on last step after using the puppet-stash class is to install (from repositories if possible) and link the mysql connector to the stash home directory.
`ln -s /usr/share/java/mysql-connector-java.jar /srv/atlassian/application-data`

**Comment by pdirksen** [comment]
Actually loading mysql-connector-java.jar from repositories is a bad idea because it still maintains the 5.1 version.

**Comment by mkrakowitzer** [comment]
Should be pretty easy to detect the JAVA_HOME from that module, So I will add that feature. I did not know openJDK was supported (its not for JIRA).

I am primarily using postgres 9.x for testing, so I will do some testing on mysql to make sure there are no manual steps required.

**Comment by mkrakowitzer** [comment]
I have added proper testing for Debian, however using postgresql for now.
I will add some beaker tests for mysql soon.

Re setting the javahome. I can not find a reliable way to set this using the java module. Best I can come up with in your case would be:
javahome => $java::java_home (This is untested).

**Comment by mkrakowitzer** [comment]
Debian support has been included for some time, and the java mysql connector is now resolved. FYI Atlassian does not recommend using MySQL with stash any more. See https://confluence.atlassian.com/display/STASH/Connecting+Stash+to+MySQL
