### ISSUE TITLE
Add an option for context path

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-stash#32]
Hi,

it would be great, if this modul has an option to set the context path. For example, if i had the path example.com/stash/, I have to set the context path to /stash.

**Comment by mkrakowitzer** [comment]
This update is now also pushed to the forge, closing this issue.

**Comment by jkroepke** [comment]
Thank you.

**Comment by mkrakowitzer** [comment]
No problem, if you would not mind taking the time to rate this module on the forge. Any honest feedback I can get helps :)
