### ISSUE TITLE
useradd create homedir problem

### ISSUE THREAD

**Issue by syss** [voxpupuli/puppet-stash#36]
When using this module on Debian wheezy the useradd command fails with 
`Error: Could not create user stash: Execution of '/usr/sbin/useradd -g stash -c Stash daemon account -d /opt/atlassian/application-data/stash-home -p * -s /bin/bash -m stash' returned 12: useradd: cannot create directory /opt/atlassian/application-data/stash-home`

I think this is because the useradd does not use `mkdir -p`.
After creating the subfolders with `mkdir -p /opt/atlassian/application-data` it seems to work

Maybe `-m` and `-b` will help with useradd

`root@host:/opt# uname -a
Linux host 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux`

**Comment by mkrakowitzer** [comment]
Yeah the parent directories will not be created for the home or the data directory, you will need to take care of that prior to calling the stash class. If you use the defaults which is /home/stash or /opt/stash. It should work fine without needing to do this. 

Unfortunatly the file type does not allow for this, its documented here:https://projects.puppetlabs.com/issues/86

It would be hard for me to cator for the parent dirs without an exec { 'mkdir -p /foo/bar'': } which is not desirable.

**Comment by Z3r0Sum** [comment]
So, how can I manage the installdir via puppet, which is where the homedir will be created, if you're declaring it within your install.pp (line: 72-77)?  If I'm provisioning a new server and want to have that installdir get created via puppet as a part of this process, it seems to fall over, or am I missing something?  I guess I could use an exec, but that's kind of lame.  Feels like the user should exist, create the installdir, and then subsequently create the stash homedir if you're going to manage all these components, which seems fair.  What are your thoughts?  I might be way off base here and missing something entirely.

**Comment by mkrakowitzer** [comment]
You need to have all the parent directories already created.

lets say installdir is '/opt/mydir'. This should work fine because /opt already exists. If installdir is '/opt/my/special/install/dir' you will need to take care of that prior to calling the stash module.

so something like this:

``` puppet
file { ['/opt/my', '/opt/my/special', '/opt/my/special', '/opt/my/special/install' ]:
  ensure => directory,
} ->

class { 'stash':
  installdir => '/opt/my/special/install/dir',
}
```

I hope this clears things up a bit.

**Comment by Z3r0Sum** [comment]
Yeah, thanks.

**Comment by mkrakowitzer** [comment]
@Z3r0Sum Can I close this issue?

**Comment by Z3r0Sum** [comment]
@mkrakowitzer Yes, thanks.
