### ISSUE TITLE
MySQL Connector Management

### ISSUE THREAD

**Issue by lodgenbd** [voxpupuli/puppet-stash#37]
I see your Jira module has MySQL connector management. Do you have any reservations regarding adding it to this module? If you don't have time, I can work on adding it and testing.

**Comment by mkrakowitzer** [comment]
I am happy to work on this, I actually think perhaps it should be its own module? Otherwise there is going to be a lot of duplicate code.

**Comment by lodgenbd** [comment]
Agreed.

**Comment by mkrakowitzer** [comment]
I have created the below puppet module to handle this:
https://github.com/mkrakowitzer/puppet-mysql_java_connector

Will integrate it into my stash/jira/confluence/bamboo modules shortly.

**Comment by mkrakowitzer** [comment]
resolved.
