### ISSUE TITLE
update .travis.yaml to deploy to puppet-community

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-stash#52]
@nibalizer @igalic Could you help me with this? I have copied my .travis.yml  updates from another module here. But I am not sure what to do about the passwd.

**Comment by nibalizer** [comment]
I've created #54 which has the encrypted password. You can just bring that into #53 no need to merge that branch or preserve commits or anything.

**Comment by mkrakowitzer** [comment]
@nibalizer @igalic @daenney 

The module released to the forge perfectly when releasing a tag, I do get some errors as it tries to deploy multiple times (https://travis-ci.org/puppet-community/puppet-stash/builds/55363904), any idea how to resolve this?

```
dpl.2
Preparing deploy
/usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/puppet-community/puppet-stash/.git/logs/refs/stash: Directory nonexistent
dpl.3
Deploying application
Uploading to Puppet Forge puppet/stash
No stash found.
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/puppet-blacksmith-3.2.0/lib/puppet_blacksmith/forge.rb:62:in `rescue in push!': Error uploading /home/travis/build/puppet-community/puppet-stash/pkg/puppet-stash-1.2.2.tar.gz to the forge https://forgeapi.puppetlabs.com [409 Conflict]: {"errors":["A release with the version specified in the metadata.json already exists for this module."]} (Blacksmith::Error)
```

**Comment by nibalizer** [comment]
See: https://github.com/puppet-community/puppetcommunity-extlib/blob/master/.travis.yml 
Specifying the matrix with puppetversion prevents the error you are seeing.

**Comment by igalic** [comment]
and makes the tests run quicker ;)

**Comment by liamjbennett** [comment]
I ran into the exact same problems. I will raise a PR to improve the docs around this.

**Comment by mkrakowitzer** [comment]
Thanks all,

On an unrelated issue would you guys consider setting up a mailing list for the puppet community? Either that or possibly a dedicated repository where I could ask questions (as issues).

I have questions from time to time (Want to make sure I do the right thing), and I feel awkward sending you all emails directly.

**Comment by liamjbennett** [comment]
I think +1 for a google group.

**Comment by nibalizer** [comment]
Yep. https://groups.google.com/forum/#!forum/puppet-community that got set up last week sometime.
