### ISSUE TITLE
Could not find class staging

### ISSUE THREAD

**Issue by miked63017** [voxpupuli/puppet-stash#56]
I may be missing something in my configuration, but I am getting the following error:
Could not find class staging
When I change to deploy I get an error saying something about invalid type deploy::file

Note: I am using puppet apply and a masterless setup, I am not sure if thats related due to autoloading or similar. But I am not really familiar with the syntax being used in here since I dont see a deploy::file defined type nor do I see a class named staging and its required. 

Anybody know what I am missing?

**Comment by mkrakowitzer** [comment]
I think you are missing the prerequisite modules. Have you installed the staging module? If you are running RHEL6, you should also install the repoforge module.

https://forge.puppetlabs.com/puppet/stash/dependencies

**Comment by miked63017** [comment]
That was it thanks! I do have a feature request: allow a way to use a proxy
for deploy and staging, I got it working by passing env to staging:file and
environment to deploy:file. Thanks for this module its working well.

**Comment by mkrakowitzer** [comment]
We have this problem too, being behind the corporate firewall and so many of the modules we use need to connect to the Internet to work. We work around it with the below in out site.pp

``` puppet
Exec {
  path => '/usr/bin:/usr/sbin/:/bin:/sbin',
  environment => [
    'http_proxy=http://proxy.example.co.za:8080',
    'https_proxy=http://proxy.example.co.za:8080',
    'ftp_proxy=http://proxy.example.co.za:8080',
    'no_proxy=localhost,127.0.0.1,.example.co.za,.foo.co.za',
  ],
}
```

**Comment by igalic** [comment]
This will still fail for puppet native types/providers, but it's a good start…

**Comment by mkrakowitzer** [comment]
I am going to close this issue, and add a new one to add proxy support to the stash module.

@miked63017 I do not recommend using the deploy module, It will be dropped from all my modules soon and replaced with nanlui-archive.
