### ISSUE TITLE
Add proxy support for downloading the stash binary.

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-stash#57]

**Comment by ffrank** [comment]
So we are using the `staging` module to do this? Does that have proxy support at all?

**Comment by nibalizer** [comment]
1) We should probably migrate to nanliu/archive on the next major release
2) Is it a module's job to configure proxy? If an http_proxy is being used then it should be set at the system level and staging/archive should honor that. We use gozerhp/puppet-setproxy to set those things at work.

**Comment by mkrakowitzer** [comment]
It also uses a module called deploy, This was before I knew staging existed. At the moment there is support for deploy or staging, with staging being the default. Both staging via the param $environment and deploy, via the param $env could support a proxy parameter.

I think next release should drop deploy, and make nanliu/archive the default, but maintain support for the staging module to remain backwards compatible. nanliu-archive requires you have a specific gem installed on your master/server.

I cannot find gozerhp/puppet-setproxy on the forge, just github, but we set out proxy in a similar way, including setting the default proxy for exec in site.pp as mentioned here: https://github.com/puppet-community/puppet-stash/issues/56

I'm not sure if the module should manage the proxy or not :( It should be trivial to add this functionality.

**Comment by ffrank** [comment]
`puppet-stash` should not manage proxy settings directly. Not even indirectly. The user should do this at profile level.

As a user, I would expect that the Puppet agent honors system wide proxy settings, especially (but not only) when the agent controls these settings. Individual modules should strive to be no exception from this rule.

All this being said, if we rely on a third party module for transport, then proxies should not be _our_ concern.

**Comment by nibalizer** [comment]
Agree 100% with frank.

**Comment by igalic** [comment]
so much learning in this thread ;)
