### ISSUE TITLE
Support Oracle as a backend database

### ISSUE THREAD

**Issue by jfautley** [voxpupuli/puppet-stash#60]
The documentation for this module indicates that only MySQL and PostgreSQL are supported databases for Stash.

It looks like all that's required is to ensure the JDBC connector is installed as well as setting the database driver/connection options correctly as per the existing My/PostgreSQL setup - or is there something bigger preventing providing Oracle support?

**Comment by mkrakowitzer** [comment]
The documentation reads as follows "Stash requires a relational database to store its configuration data. This module currently supports PostgreSQL 8.4 to 9.x and MySQL 5.x. We suggest using puppetlabs-postgresql/puppetlabs-mysql modules to configure/manage the database. The module uses PostgreSQL as a default."

I don't believe it indicates that these are the only databases that stash supports, it only implies that these are the databases that this module supports.

I think you are spot on with whats required to implement (plus tests). It should be rather trivial. It would be nice to have acceptance tests for oracle too, that may prove more challenging however and I do not think it is a must have for oracle support to be added.

**Comment by igalic** [comment]
maybe there's a vagrant box somewhere out there with a pre-installed oracle db?

**Comment by nibalizer** [comment]
@igalic probably not because oracledb is closed. Same problem with mssql. If we can find one I can add it to pcci though.

**Comment by nanliu** [comment]
I was able to install against Oracle with stash 3.8 and the following db settings with no module changes:

``` yaml
---
  stash::dburl: 'jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.lan)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = stash)))'
  stash::dbuser: 'stash'
  stash::dbpassword: 'stash_password'
  stash::dbdriver: 'oracle.jdbc.driver.OracleDriver'
```

It did not prompt for db settings during setup, and appears to connect after installation. Acceptance test will be non trivial even with biemond-oracle module. This can be documented, but promising module support for Oracle is another level of challenge altogether.

**Comment by nibalizer** [comment]
@jfautley sounds like you've got your answer. If someone wants to they can sumarize nan's experience as a sidebar in the readme.
