### ISSUE TITLE
stash backup should be able to cleanup old archives

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-stash#61]
So today i ran into a curious issue:

```
igalic@levix ~/src/bw/puppet/environments/production (git)-[production] % git push origin production
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 538 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: error: file write error (No space left on device)
remote: fatal: unable to write sha1 file
error: unpack failed: unpack-objects abnormal exit
To ssh://git@stash.esotericsystems.at:7999/infra/puppet-environment.git
 ! [remote rejected] production -> production (unpacker error)
error: failed to push some refs to 'ssh://git@stash.esotericsystems.at:7999/infra/puppet-environment.git'
1 igalic@levix ~/src/bw/puppet/environments/production (git)-[production] %
```

the culprit of the `remote: error: file write error (No space left on device)` was stasbackup.
i think it might be useful to have a cleanup job, that deletes archives older than $n days.

**Comment by mkrakowitzer** [comment]
OK fair enough. Any suggestions on the best way to go about it, or how you would prefer to see this implemented? The quick and nasty would be the tidy type.

**Comment by igalic** [comment]
oh?
what's that?

**Comment by mkrakowitzer** [comment]
https://docs.puppetlabs.com/references/latest/type.html#tidy

The downside or upside depending on how you look at it is when it cleans up a file, the puppet run shows as 'changed'

**Comment by igalic** [comment]
:+1:

makes me wonder why the puppet labs MySQL module doesn't use it, but the answer is of course because the contribution came from outside and some eagerly pressed merge ;)
