### ISSUE TITLE
Add paramaters for stash 3.8 Automated setup options

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-stash#63]
Previously, even when installing Stash automatically, you still had to visit the Stash Setup Wizard in the browser to set the admin account, the Base URL and the external database connection, and to add the Stash license. 

Now, by specifying all those settings in the Stash config properties file, you can completely install and set up a Stash instance automatically, without manual intervention. Stash will read the file, and apply those settings automatically after launching.

Its documented here:
https://confluence.atlassian.com/display/STASH/Automated+setup+for+Stash

**Comment by igalic** [comment]
♥
