### ISSUE TITLE
Tomcat port should be configurable.

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-stash#64]
Currently defaults to 7990 in the server.xml. This should be configurable with a parameter.

**Comment by stack72** [comment]
@mkrakowitzer had a few spare minutes so started configuring this 

https://github.com/stack72/puppet-stash/commit/a39f6f4ae8e23e78a27704df5114416690a89207

Will finish the specs and send a PR today at some point

**Comment by igalic** [comment]
@stack72 i'd just call it port, rather than tomcat_port

**Comment by mkrakowitzer** [comment]
I think @stack72 is trying to keep it the same as the confluence module which already has the parameter tomcat_port. Whilst I agree port might have been better, i would prefer to keep the params between confluence, stash and jira the same or as close as possible.

**Comment by stack72** [comment]
There are multiple ports specified across server.XML so thought I would be specific

**Comment by stack72** [comment]
@mkrakowitzer https://github.com/puppet-community/puppet-stash/pull/66 :)

**Comment by mkrakowitzer** [comment]
Thanks, merged.

If you have not rated the stash module on the forge, please consider doing so :)

TIA.
