### ISSUE TITLE
upgrading to  > 3.8 does not use the correct setenv.sh

### ISSUE THREAD

**Issue by micah-uber** [voxpupuli/puppet-stash#77]
From atlassian:

Starting with Stash 3.8, we removed the permgen.sh script that checked if PermGen was supported (it's been removed in Java 8). We then made the following changes to setenv.sh:
setenv.sh Stash 3.7
JAVA_OPTS="-Xms${JVM_MINIMUM_MEMORY} -Xmx${JVM_MAXIMUM_MEMORY} ${JMX_OPTS} ${JAVA_OPTS} ${JVM_REQUIRED_ARGS} ${JVM_SUPPORT_RECOMMENDED_ARGS} ${STASH_HOME_MINUSD}"
# PermGen size needs to be increased if encountering OutOfMemoryError: PermGen problems. Specifying PermGen size is
# not valid on IBM JDKs

STASH_MAX_PERM_SIZE=256m
if [ -f "${PRGDIR}/permgen.sh" ]; then
    echo "Detecting JVM PermGen support..."
    . "${PRGDIR}/permgen.sh"
    if [ $JAVA_PERMGEN_SUPPORTED = "true" ]; then
        echo "PermGen switch is supported. Setting to ${STASH_MAX_PERM_SIZE}\n"
        JAVA_OPTS="-XX:MaxPermSize=${STASH_MAX_PERM_SIZE} ${JAVA_OPTS}"
    else
        echo "PermGen switch is NOT supported and will NOT be set automatically.\n"
    fi
fi
setenv.sh Stash 3.8
JAVA_OPTS="-Xms${JVM_MINIMUM_MEMORY} -Xmx${JVM_MAXIMUM_MEMORY} ${JAVA_OPTS} ${JVM_REQUIRED_ARGS} ${JVM_SUPPORT_RECOMMENDED_ARGS} ${STASH_HOME_MINUSD}"
# PermGen size needs to be increased if encountering OutOfMemoryError: PermGen problems.

MAX_PERM_SIZE=256m
JAVA_OPTS="-XX:MaxPermSize=${MAX_PERM_SIZE} ${JAVA_OPTS}"

export JAVA_OPTS
If setenv.sh was copied over from Stash 3.7, the test to check if using PermGen is allowed always returns false since permgen.sh is no longer there and the PermGen size gets set to the default, which is too small for Stash. Upgrading to JDK 8 would resolve this as well as PermGen is no longer used and replaced with Metaspace.
I've included a fresh copy of setenv.sh from a 3.10 instance that you can use to replace the existing one if it was copied over.

**Comment by mkrakowitzer** [comment]
I believe this is already fixed in the master branch.

**Comment by micah-uber** [comment]
just confirmed... was using an old commit. thanks.

## 

Micah Figone

Senior Systems Engineer
Uber
