### ISSUE TITLE
JAVA_HOME on CentOS 7 gets doubled when /bin/java specified as java_home

### ISSUE THREAD

**Issue by claflico** [voxpupuli/puppet-stash#80]
Am using the role/profile method for setting up a stash server on minimal install of CentOS 7, here is my role config:

  include profile::git
  include profile::java
  include profile::logstashforwarder
  include profile::nginx
  include profile::postgresql
  include profile::selinux
  include profile::stash

Not sure if it's because I'm using the java module to install java but I have to leave set java_home='' otherwise when I try to start the stash service I get an error message about /bin/java/bin/java not being valid:

grep -r "/bin/java/bin/java" /mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/logs/
/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/logs/catalina.out:/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/bin/catalina.sh: line 399: /bin/java/bin/java: Not a directory
/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/logs/catalina.out:/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/bin/catalina.sh: line 399: /bin/java/bin/java: Not a directory
/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/logs/catalina.out:/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/bin/catalina.sh: line 399: /bin/java/bin/java: Not a directory
/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/logs/catalina.out:/mnt/atlassian/stash/atlassian-stash/atlassian-stash-3.10.2/bin/catalina.sh: line 399: /bin/java/bin/java: Not a directory 

Not sure if it's because it is being defined in setenv.sh.erb & stash.service.erb but somehow the value is getting doubled.

**Comment by mkrakowitzer** [comment]
JAVA_HOME, normally does not point directly to the java binary but rather the home directory where java is installed to. Based on where your java binary is located I would expect your JAVA_HOME to be '', You JAVA_PATH would be /bin/java. 

Not sure if this helps?

**Comment by claflico** [comment]
When I look at /bin/java it looks like the path is: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre-abrt/bin/java

When I look in /usr/lib/jvm/ I see several java folders so I might try setting it to /usr/lib/jvm/java-1.7.0-openjdk

Thanks

**Comment by mkrakowitzer** [comment]
If you are using the puppetlabs java module, I think you can set java home like this (untested):

``` puppet
javahome => $java::java_home
```

**Comment by mkrakowitzer** [comment]
Hi Claflico, where you able to resolve your issue? Can this be closed?

**Comment by claflico** [comment]
I got it figured out. thanks for the help.
