### ISSUE TITLE
setenv.sh.erb not compatible with stash 3.10.2

### ISSUE THREAD

**Issue by claflico** [voxpupuli/puppet-stash#81]
The setenv.sh template is not compatible with 3.10.2. Upgraded our stash server from 2.12.0 to 3.10.2 over the weekend and couldn't get it to run reliably as the java load would shoot up and not go back down until stash crashed. Submitted a ticket with atlassian and after reviewing the support packet they said that the setenv.sh file we were trying to use (from this module) was no longer compatible after 3.7.

https://confluence.atlassian.com/display/STASHKB/Stash+crashes+due+to+java.lang.OutOfMemoryError+PermGen+Space+Error

**Comment by mkrakowitzer** [comment]
What java version are you using? If you are using 1.8 this should not be an issue. 

Stash no longer supports 1.7
https://confluence.atlassian.com/display/STASH/Supported+platforms

**Comment by claflico** [comment]
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.2.el7_1-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

I saw that java 1.7 was being deprecated. I'm using the puppetlabs-java plugin and it looks like for CentOS they set it to version 1.7. https://github.com/puppetlabs/puppetlabs-java/blob/master/manifests/params.pp#L29

When I search yum I see that java-1.8.0-openjdk is available but when I do "yum update" it doesn't show up as an update. This server is in production now but I'll try after hours to see if I can set the java_version to 1.8 in my hiera file.

**Comment by mkrakowitzer** [comment]
I suspect JAVA 1.8 is its own package. So it wont update

**Comment by claflico** [comment]
Just realized that this is pretty much a duplicate of: https://github.com/puppet-community/puppet-stash/issues/77

Will you be releasing a new version on the puppetlab forge site soon?

Thanks

**Comment by mkrakowitzer** [comment]
Pushed new version. Can this issue be closed?

**Comment by claflico** [comment]
Just tried the new module version and it appears to work, thanks for the help.
