### ISSUE TITLE
Feature requests: Don't have backup deletion managed by puppet. 

### ISSUE THREAD

**Issue by claflico** [voxpupuli/puppet-stash#84]
I think that I can try to work on this if I get time but am putting it here just to document. The deletion of backups probably shouldn't be handled by puppet but rather a script stored locally. We had to disable the puppet agent on our stash server while troubleshooting the setenv.sh template issue and the backups almost filled the hard drive.

**Comment by mkrakowitzer** [comment]
Are you saying that the stash module should not manage the cleanups of the backups? Or that instead of using the tidy type, we should use the cron type with a script to remove old backup files?

**Comment by claflico** [comment]
Yeah, since there is already have a cron in place I would probably modify the backup_cmd to handle deleting the older files in addition to doing the backup. Not sure whether adding it to a bash script or just adding it to the command would be the better route though.

**Comment by mkrakowitzer** [comment]
claflico, would you consider submitting a PR for this? I cant justify implementing it as I feel the current method is working well for my environments.

**Comment by mkrakowitzer** [comment]
Closing this issue. Happy to reopen if you would consider submitting a patch for this feature.
