### ISSUE TITLE
allow a global parameter to all settings in stash-config.properties.erb

### ISSUE THREAD

**Issue by claflico** [voxpupuli/puppet-stash#85]
Rather than hard-coding variables & the template for each of the system properties (i.e. jdbc, setup automation, etc.) would it be possible to make all of the config options able to be managed? You shouldn't have to define defaults for each of the variables as it sounds like they are already in stash and only need to be specified if you want to override the default stash value: https://confluence.atlassian.com/display/STASH/Stash+config+properties

Our devs are wanting to add this but I told them that custom properties weren't supported by the module yet and that I wasn't wanting to snowflake the server for it: https://confluence.atlassian.com/display/STASH/Stash+config+properties#Stashconfigproperties-Pullrequests

**Comment by mkrakowitzer** [comment]
resolved

**Comment by claflico** [comment]
Awesome, when you get the version on forge updated I'll try to give it a try.

Thanks!
