### ISSUE TITLE
Download of backup client fails

### ISSUE THREAD

**Issue by exptom** [voxpupuli/puppet-stash#87]
The url structure appears to have changed to this:

```
https://maven.atlassian.com/public/com/atlassian/stash/backup/stash-backup-distribution/<version>/stash-backup-distribution-<version>.zip
```

**Comment by exptom** [comment]
Just realised I can get around the issue with this in my hiera file:

```
stash::backupclientURL: 'https://maven.atlassian.com/public/com/atlassian/stash/backup/stash-backup-distribution/1.9.1/'
stash::backupclientVersion: '1.9.1'
```

Without this workaround the module fails to install with the default setting.

**Comment by mkrakowitzer** [comment]
Thanks for reporting this as well as the solution, I will take a look shortly and provide a fix.
