### ISSUE TITLE
Add support for stash 4.0 (Bitbucket Server) 

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-stash#92]
Stash has been renamed to Bitbucket Server, it likely will no longer work with the module as is.

We should add support for Bitbucket Server, and attempt remain backward compatible with with stash 3.x

**Comment by pgold30** [comment]
Thnks for this module, i have a question is this working for stash/bitbucket 4.0.2?

**Comment by mkrakowitzer** [comment]
No not yet, support is in the works.

**Comment by pgold30** [comment]
o ok, do you have an aprox idea of release date? another question i want to use your stash jira(already working great) and bamboo as a suite , is possible to set this in manifests of puppet? or just install all one by one in different servers and then create aplications links? Thanks for your quick answer

**Comment by stefanlasiewski** [comment]
pgold30, this topic is in regards to support for Bitbucket Server 4.x and we don't want bug reports to go off topic. You can monitor the progress of the 4.x branch at https://github.com/puppet-community/puppet-stash .

I recommend that you ask your non-4.x questions in https://groups.google.com/forum/#!forum/puppet-community , as the Puppet community supports this module.

**Comment by jeski** [comment]
Wondering if this is/will be tested for the future parser?

**Comment by preflightsiren** [comment]
I actually think we should fork the module and do a bit of a redesign. There's enough changes between stash->bb to warrant it IMO, not least is all the download URLs

**Comment by mkrakowitzer** [comment]
Sebastian I have something in the works, its working but is has no upgrade
path from 3 to 4, and I don't have the time to finish it right now,
interested?

**Comment by preflightsiren** [comment]
not sure I'll have time to really nut it out, the migration support could be a bit tricky :\ have you got a branch I can checkout?

**Comment by mkrakowitzer** [comment]
Its not a fork, Its a rewrite, this module has been around since puppet 2, so it has lots of cruft and I thought it made sense to just start again. I just committed it now https://github.com/mkrakowitzer/puppet-bitbucket

It has working beaker tests, no unit tests, no documentation. Sorry :(

**Comment by spacepants** [comment]
Hey there, I've gone ahead and finished out the bitbucket [unit tests](https://travis-ci.org/spacepants/puppet-bitbucket) and [documentation](https://github.com/spacepants/puppet-bitbucket) to get it as ready for primetime as I can since I needed it for my environment anyway.

I have an [open pr](https://github.com/mkrakowitzer/puppet-bitbucket/pull/1), but @mkrakowitzer seems to be a bit preoccupied at the moment. What do I need to do to release this to puppet community?

**Comment by jyaworski** [comment]
@spacepants please submit it against voxpupuli. We can review it there. After that, I'll close this one.

**Comment by spacepants** [comment]
> please submit it against voxpupuli.

Do you mean against voxpupuli/stash, or as a new, separate module? It originally started out as a rewrite of the stash module instead of a fork, so the diff is fairly substantial.

**Comment by chihoko** [comment]
Is support for upgrading from 3.x to 4.x working yet?

**Comment by micah-uber** [comment]
What is the status of bitbucket support?

**Comment by jyaworski** [comment]
@spacepants against stash.

**Comment by emrtldrgn** [comment]
Just following up here. Any updates?

**Comment by mkrakowitzer** [comment]
Vz

**Comment by SimonHoenscheid** [comment]
The module works with recent versions

**Comment by igalic** [comment]
closing as resolved
